### ISSUE TITLE
This doesn't install Dashboard, how can we do that?

### ISSUE THREAD

**Issue by shreekant** [anubhavmishra/terraform-azurerm-aks#3]
I tried the solution and it works fine, But this doesn't install Dashboard, how can we do that?

**Comment by shreekant** [comment]
@anubhavmishra Please have a look at this issue and let me know if there are documents for this.

**Comment by anubhavmishra** [comment]
@shreekant the Terraform configuration doesn't install Kubernetes dashboard as it only helps you create an AKS cluster. AKS comes with Kubernetes already installed. I looked at the Azure documentation to see how they enable Kubernetes dashboard access and I found the following commands:

```bash
az aks browse --resource-group aksdemo-rg --name aksdemo1
```

Expected output:

```bash
Merged "aksdemo1" as current context in /var/folders/wz/q53m4kn10hv6z20jvvv39_6h0000gn/T/tmpsxd8ffvj
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
```

To access the dashboard run the following command.

```bash
open http://127.0.0.1:8001/
```

[Here](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard) is the link to the AKS documentation about accessing the Kubernetes dashboard.

Please note, in the above example I am using the default resource group `aksdemo-rg` and cluster name `aksdemo1`.

Please do let me know if that worked for you. :)

**Comment by shreekant** [comment]
Hi @anubhavmishra  Thanks for your reply, i debugged into this and found we can use the dashboard from http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

**Comment by anubhavmishra** [comment]
@shreekant the Kubernnetes dashboard at (http://127.0.0.1:8001/) automatically redirects to the long formed url. You don't need to go to the long-form url directly. I am going to close this issue.
